### ISSUE TITLE
Privacy violation

### ISSUE THREAD

**Issue by lowbox** [lumpchen/xdiff.ncc#2]
**Describe the bug**
user submit data is undelete in http://pdfdict.com . pelease delete it for unnecessary trouble

**Comment by lumpchen** [comment]
@lowbox , thanks for your mention. Of course,  I  take privacy seriously.  It's true that I haven't individually deleted each uploaded file. But all uploaded files are deleted regualy, pdfdict.com sets a timer to clear the upload directory.
